//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RejestrOsobZaginionych.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MissingPeople
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Imiê")]
        public string Imie { get; set; }
        [Required]
        [Display(Name = "Nazwisko")]
        public string Nazwisko { get; set; }
        [Required]
        [Display(Name = "Miejsce zamieszkania")]
        public string MiejsceZamieszkania { get; set; }
        [Required]
        [Display(Name = "Miejsce zaginiêcia")]
        public string MiejsceZaginiecia { get; set; }
        [Required]
        [Display(Name = "Wiek")]
        public int Wiek { get; set; }
        [Required]
        [Display(Name = "P³eæ")]
        public string Plec { get; set; }
        [Required]
        [Display(Name = "Opis")]
        public string Opis { get; set; }
        //[Required(ErrorMessage ="Za³¹cz zdjêcie (w formacie JPG)")]
        [Display(Name = "Zdjêcie")]
        public byte[] Zdjecie { get; set; }

        [Display(Name = "Login")]
        public string UserName { get; set; }
        [Display(Name = "Rola")]
        public string Role { get; set; }
        [Display(Name = "Aktywny")]
        public string Active { get; set; }
    }
}
